language: python
python:
  - 2.7
  - 3.4
env:
  - DJANGO=django==1.8.17
  - DJANGO=django==1.9.12
  - DJANGO=django==1.10.5
matrix:
  fast_finish: true
install:
  - travis_retry pip install $DJANGO
  - pip install -e .
script: python runtests.py
notifications:
  email: false
